module Crokus

  class PrinterC

    attr_accessor :cfg

    def initialize
      @visited=[]
      @prp=PrettyPrinter.new
    end

    def print cfg
      puts " |-->[+] generating C code from cfg '#{cfg.name}'"
      @cfg=cfg
      code=Code.new
      code << "//"+"-"*60
      code << "// automatically generated by Crokus compiler"
      code << "// date : #{Time.now.strftime("%a %d,%B %Y - %H:%M:%S")}"
      code << "//"+"-"*60
      code.newline
      code << "int #{cfg.name}(#{}){"
      code.indent=2
      code << visit_rec(cfg.starter)
      code << "return 0;"
      code.indent=0
      code << "}"
      puts code.finalize
      code.save_as "#{cfg.name}.c"
    end

    def visit_rec bb
      unless bb.nil? or @visited.include?(bb)
        if bb.infos[:start_if]
          gen_if(bb)
        elsif bb.infos[:start_while]
          gen_while(bb)
        elsif bb.infos[:start_for]
          gen_for(bb)
        else
          gen_plain(bb)
        end
      end
    end

    def gen_plain bb
      code=Code.new
      @visited << bb
      code << "// bb #{bb.label}"
      bb.stmts.each{|assign|
        code << assign.accept(@prp)
      }
      code << visit_rec(bb.nextBranch)
      code
    end

    def gen_if bb
      code=Code.new
      @visited << bb
      code << "// bb 'if' #{bb.label}"
      bb.stmts.each{|stmt| code << stmt.accept(@prp)}
      code << "if (#{}){"
      code.indent=2
      code << visit_rec(bb.trueBranch)
      code.indent=0
      code << "}"
      code << "else {"
      code.indent=2
      code << visit_rec(bb.falseBranch)
      code.indent=0
      code << "}"
      code
    end

    def gen_while bb
      code=Code.new
      @visited << bb
      code << "// bb 'while' #{bb.label}"
      bb.stmts.each{|stmt| code << stmt.accept(@prp)}
      cond=bb.infos[:cond].accept(@prp)
      code << "while (#{cond}){"
      code.indent=2
      code << visit_rec(bb.trueBranch)
      code.indent=0
      code << "}"
      code << visit_rec(bb.falseBranch)
      code
    end

    def gen_for bb
      code=Code.new
      @visited << bb
      code << "// bb 'for' #{bb.label}"
      bb.stmts.each{|stmt| code << stmt.accept(@prp)}
      index=bb.infos["loop_index"]
      index_bound=bb.infos["loop_index_bound"]
      code << "for(int #{index}=0;#{index} < #{index_bound};#{index}++){"
      code.indent=2
      code << visit_rec(bb.trueBranch)
      code.indent=0
      code << "}"
      code << visit_rec(bb.falseBranch)
      code
    end
  end
end
